@host = http://localhost:5281

GET {{host}}/weatherforecast/
Accept: application/json

### criar um novo canal (payload)

POST {{host}}/api/v1/canais
Content-Type: application/json

{
    "nome": "Receitas Culinárias da Marta"
}

### listar todos os canais

GET {{host}}/api/v1/canais
Accept: application/json
